# Anchor configuration
[programs.localnet]
zetamint = "EteYkYdk3kTpHYqzc6Exrx9JqZDF2n2jw53sF318oKiU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
[scripts]
# If you have mocha JS tests at repo root: tests/*.ts
# Otherwise, adjust to `anchor test` or remove this section.
test = "yarn run mocha"
