[features]
seeds = false
skip-lint = false

[programs.localnet]
universal_nft = "7Y4yxx8znoASMCAUGE2NUv6kWKgmpzYFRejc2dwaqpEK"

[programs.devnet]
universal_nft = "7Y4yxx8znoASMCAUGE2NUv6kWKgmpzYFRejc2dwaqpEK"

[programs.testnet]
universal_nft = "7Y4yxx8znoASMCAUGE2NUv6kWKgmpzYFRejc2dwaqpEK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
channel = "1.78.0"
anchor_version = "0.29.0"
